"""empty message

Revision ID: 88f7e9ba85d8
Revises: 199a5ddb1fa0
Create Date: 2021-06-01 14:08:30.568355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f7e9ba85d8'
down_revision = '199a5ddb1fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotels', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hotels', 'add_country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'country_id')
    op.drop_table('add_country')
    # ### end Alembic commands ###
